# Generated by Django 3.2.7 on 2022-07-02 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend_lst',
            field=models.ManyToManyField(blank=True, null=True, related_query_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
