# Generated by Django 3.2.7 on 2022-06-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_customisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
