# Generated by Django 3.2.7 on 2022-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_customisation', '0002_blog_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
