# Generated by Django 3.2.7 on 2022-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Publish'), ('pr', 'Private')], default='df', max_length=100),
        ),
    ]
