# Generated by Django 3.2.7 on 2022-07-07 14:55

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220707_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_email',
            field=models.CharField(max_length=100, null=True, validators=[blog.validators.email_validator]),
        ),
    ]
