# Generated by Django 3.2.7 on 2022-07-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('df', 'Draft'), ('pb', 'Public'), ('pr', 'Private')], default='df', max_length=100),
        ),
    ]
